all:
  children:
    linux:
      hosts:
        vps12:
          ansible_host: 192.168.214.12
          ansible_user: powerseven-bootstrap
        vps14:
          ansible_host: 192.168.214.14
          ansible_user: powerseven-bootstrap
    windows:
      hosts:
        vps13:
          ansible_host: 192.168.214.13
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_transport: ntlm
    powerseven:
      hosts:
        vps12:
        vps13:
        vps14:
